version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    #image: koenkk/zigbee2mqtt:arm32v6
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt/data/:/app/data
      - ./zigbee2mqtt/zigbee-shepherd-converters/:/app/node_modules/zigbee-shepherd-converters/
      - ./zigbee2mqtt/lib/extension/homeassistant.js:/app/lib/extension/homeassistant.js
    devices:
      # CC251
      - /dev/ttyACM0:/dev/ttyACM0
      # CC2530 / GBAN GB2530S
      #- /dev/ttyUSB_cc2530:/dev/ttyACM0
    #restart: always
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
#    ports:
#      - "1883:1883"
#      - "9001:9001"
    network_mode: host
    volumes:
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./mosquitto/data:/mosquitto/data"
  homeassistant:
    container_name: home-assistant
#    image: homeassistant/raspberrypi3-homeassistant:0.98.0
    image: homeassistant/raspberrypi3-homeassistant:2021.6.4 #:0.114.3
    volumes:
      - ./homeassistantconfig:/config
      - /etc/localtime:/etc/localtime:ro
      # - ./sslcert:/sslcert
    #restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Madrid
      - SUBDOMAINS=savir
      - FILE__TOKEN=/config/token
      - LOG_FILE=false #optional
    volumes:
      - ./duckdns:/config #optional
    restart: unless-stopped      

