title: Casa
views:
  - badges:
      - entity: binary_sensor.updater
    cards:
      - entity: input_boolean.notify_telegram
        hold_action:
          action: more-info
        icon_height: 40px
        show_icon: true
        show_name: true
        show_state: false
        tap_action:
          action: toggle
        type: button
      - entities:
          - entity: binary_sensor.0x00158d00034fb778_occupancy
          - entity: sensor.tiempo_sin_movimiento_entrada
          - entity: binary_sensor.0x00158d00032614ea_contact
          - entity: sensor.0x00158d00034fb778_linkquality
          - entity: sensor.0x00158d00032614ea_linkquality
          - entity: sensor.0x00158d00032614ea_battery
          - entity: sensor.0x00158d00034fb778_battery
        show_header_toggle: false
        title: Entrada
        state_color: null
        type: entities
      - entities:
          - entity: binary_sensor.zigbee_puerta_cocina
          - entity: sensor.tiempo_sin_movimiento_cocina
          - entity: binary_sensor.0x00158d0003d0c052_contact
          - entity: sensor.0x00158d0003d0c052_linkquality
          - entity: sensor.0x00158d0003f4772c_illuminance
          - entity: sensor.0x00158d0003f4772c_linkquality
          - entity: sensor.0x00158d0003d0c052_battery
          - entity: sensor.0x00158d0003f4772c_battery
        show_header_toggle: false
        title: Cocina
        type: entities
      - entity: weather.casa
        type: weather-forecast
      - entities:
          - entity: sensor.0x00158d000374adb8_click
          - entity: sensor.0x00158d000374adb8_action
          - entity: sensor.0x00158d000374adb8_battery
          - entity: sensor.0x00158d000374adb8_linkquality
        title: Boton
        type: entities
#      - type: glance
#        entities:
#          - entity: binary_sensor.zigbee_puerta_cocina
#          - entity: binary_sensor.0x00158d00032614ea_contact
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - input_select.zigbee2mqtt_log_level
          - input_text.zigbee2mqtt_new_name
          - input_text.zigbee2mqtt_old_name
          - input_text.zigbee2mqtt_remove
          - script.zigbee2mqtt_remove
          - script.zigbee2mqtt_rename
          - sensor.coordinator_version
          - sensor.zigbee2mqtt_bridge_state
          - sensor.zigbee2mqtt_version
          - switch.zigbee2mqtt_main_join
          - timer.zigbee_permit_join
        show_header_toggle: true
        title: Zigbee
        type: entities
    path: configuracion
    title: Configuracion
  - badges: []
    cards:
      - css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(18, 120, 98, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #dcfaf3;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(18, 120, 98, .5);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #127862;
            --zigbee2mqtt-networkmap-arrow-color: rgba(18, 120, 98, 0.7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
          }
        entity: sensor.zigbee2mqtt_networkmap
        font_size: 12
        force: 3000
        height: 400
        link_width: 2
        mqtt_base_topic: zigbee2mqtt
        node_size: 16
        type: 'custom:zigbee2mqtt-networkmap'
    panel: true
    path: mapa
    title: Mapa