title: Casa
views:
  - badges: []
#      - type: state-badge
#        entity: binary_sensor.0x00158d00034fb778_occupancy
#      - entity: binary_sensor.0x00158d00032614ea_contact
#      - entity: binary_sensor.zigbee_puerta_cocina
#      - entity: binary_sensor.0x00158d0003d0c052_contact
    cards:
      - type: glance
        entities:
          #- entity: binary_sensor.zigbee_puerta_cocina
          #  name: Cocina
          #- entity: binary_sensor.0x00158d0003d0c052_contact
          #  name: Cocina
          #- entity: binary_sensor.0x00158d00034fb778_occupancy
          #  name: Entrada
          #- entity: binary_sensor.0x00158d00032614ea_contact
          #  name: Entrada
          - entity: input_boolean.notify_telegram
            name: Telegram
            tap_action:
              action: toggle
            hold_action:
              action: more-info
          - entity: input_boolean.fuera_de_casa
            name: Fuera de Casa
            tap_action:
              action: toggle
            hold_action:
              action: more-info  
        show_state: false
      - type: picture-elements
        elements:
        - type: state-icon
          entity: binary_sensor.0x00158d0003d0c052_contact
          style:
            top: 50.5%
            left: 8%
        - type: state-icon
          entity: binary_sensor.zigbee_puerta_cocina
          style:
            top: 58%
            left: 8%
        - type: state-icon
          entity: binary_sensor.0x00158d00032614ea_contact
          style:
            top: 95%
            left: 53%
        - type: state-icon
          entity: binary_sensor.0x00158d00034fb778_occupancy
          style:
            top: 96%
            left: 59%    
        - type: image #state-icon
          entity: camera.entrada_casa
          title: ""
          camera_image: camera.entrada_casa
          style:
            top: 66%
            left: 54%
      #width: 20%
        - type: state-icon
          entity: camera.entrada_cocina
          title: ""
          camera_image: camera.entrada_cocina
          style:
            top: 45%
            left: 10%
            width: 10%
      #width: 20%    
    
        image: /local/mapa_rivas.png
#      - entity: input_boolean.notify_telegram
#        hold_action:
#          action: more-info
#        icon_height: 40px
#        show_icon: true
#        show_name: true
#        show_state: false
#        tap_action:
#          action: toggle
#        type: button
      - type: picture-glance
        title: Cocina
        entities: 
        - binary_sensor.0x00158d0003d0c052_contact
        - binary_sensor.zigbee_puerta_cocina
        camera_image: camera.entrada_cocina
      - type: picture-glance
        title: Entrada
        entities: 
        - binary_sensor.0x00158d00032614ea_contact
        - binary_sensor.0x00158d00034fb778_occupancy
        camera_image: camera.entrada_casa
      - type: custom:auto-entities
        card:
          type: entities
          title: Automatizaciones
        filter:
          include:
          - domain: automation    
      - entity: weather.casa
        type: weather-forecast
#      - type: glance
#        entities:
#          - entity: binary_sensor.zigbee_puerta_cocina
#          - entity: binary_sensor.0x00158d00032614ea_contact
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.zigbee_puerta_cocina
          - entity: sensor.tiempo_sin_movimiento_cocina
          - entity: binary_sensor.0x00158d0003d0c052_contact
          - entity: sensor.0x00158d0003d0c052_linkquality
          - entity: sensor.0x00158d0003f4772c_illuminance
          - entity: sensor.0x00158d0003f4772c_linkquality
          - entity: sensor.0x00158d0003d0c052_battery
          - entity: sensor.0x00158d0003f4772c_battery
        show_header_toggle: false
        title: Cocina
        type: entities
      - entities:
          - entity: binary_sensor.0x00158d00034fb778_occupancy
          - entity: sensor.tiempo_sin_movimiento_entrada
          - entity: binary_sensor.0x00158d00032614ea_contact
          - entity: sensor.0x00158d00034fb778_linkquality
          - entity: sensor.0x00158d00032614ea_linkquality
          - entity: sensor.0x00158d00032614ea_battery
          - entity: sensor.0x00158d00034fb778_battery
        show_header_toggle: false
        title: Entrada
        state_color: true
        type: entities
      - entities:
          - entity: sensor.0x00158d000374adb8_click
          - entity: sensor.0x00158d000374adb8_action
          - entity: sensor.0x00158d000374adb8_battery
          - entity: sensor.0x00158d000374adb8_linkquality
        title: Boton
        type: entities  
      - entities:
          - input_select.zigbee2mqtt_log_level
          - input_text.zigbee2mqtt_new_name
          - input_text.zigbee2mqtt_old_name
          - input_text.zigbee2mqtt_remove
          - script.zigbee2mqtt_remove
          - script.zigbee2mqtt_rename
          - sensor.coordinator_version
          - sensor.zigbee2mqtt_bridge_state
          - sensor.zigbee2mqtt_version
          - switch.zigbee2mqtt_main_join
          - timer.zigbee_permit_join
        show_header_toggle: true
        title: Zigbee
        type: entities
    path: configuracion
    title: Configuracion
  - badges: []
    cards:
      - css: |
          :host {
            --zigbee2mqtt-networkmap-node-color: rgba(18, 120, 98, .7);
            --zigbee2mqtt-networkmap-node-fill-color: #dcfaf3;
            --zigbee2mqtt-networkmap-node-pinned-color: rgba(190, 56, 93, .6);
            --zigbee2mqtt-networkmap-link-color: rgba(18, 120, 98, .5);
            --zigbee2mqtt-networkmap-hover-color: #be385d;
            --zigbee2mqtt-networkmap-link-selected-color: rgba(202, 164, 85, .6);
            --zigbee2mqtt-networkmap-label-color: #127862;
            --zigbee2mqtt-networkmap-arrow-color: rgba(18, 120, 98, 0.7);
            --zigbee2mqtt-networkmap-node-coordinator-color: rgba(224, 78, 93, .7);
            --zigbee2mqtt-networkmap-node-router-color: rgba(0, 165, 255, .7);
          }
        entity: sensor.zigbee2mqtt_networkmap
        font_size: 12
        force: 3000
        height: 400
        link_width: 2
        mqtt_base_topic: zigbee2mqtt
        node_size: 16
        type: 'custom:zigbee2mqtt-networkmap'
    panel: true
    path: mapa
    title: Mapa